<?php
$_items = $this->getItems();
$helper = Mage::helper('checkout');
/** @var Mage_Checkout_Block_Cart_Totals $oCartTotalBlock */
$oCartTotalBlock =  Mage::getBlockSingleton('checkout/cart_totals');
?>
<?php if($iSize = count($_items)): ?>
    <ul class="chosen-products">
        <?php $iCount = 0;  ?>
        <?php foreach ($_items as $_item): ?>
            <li class="<?php echo (($iCount++ % 2) == 0)?'zebra':'' ?>">
                <?php echo $this->getItemHtml($_item) // checkout/cart/sidebar/default.phtml as defined in minicart.xml  ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="total-qty"> <?php echo $iSize; ?> <?php echo ($iSize > 1) ? $this->__('items in cart') : $this->__('item in cart'); ?></div>
    <div class="dropdown-cart-subtotal"><?php
        echo $oCartTotalBlock->renderTotals();
        //footer so it displays grand total
        echo $oCartTotalBlock->renderTotals('footer');
        ?></div>
<?php else: ?>
    <div class="no-items-in-cart"><?php echo Mage::helper('minicart')->getEmptyCartMessage();?></div>
<?php endif ?>
<div class="action">
    <a href="<?php echo $this->getUrl('checkout/cart');?>" class="dropdown-view-cart button"><?php echo $this->__('Go to cart');?></a>
</div>
<div class="promotional">
    <?php echo Mage::helper('minicart')->getPromotionalMessage(); ?>
</div>