<?php
    //Allow translations to add something custom before items in bag
    $vBagPrefix = $this->__('BAG_PREFIX');
    //does not have any custom translation
    if ($vBagPrefix == 'BAG_PREFIX') {
        $vBagPrefix = '';
    }
?>
<?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
    <?php if ($this->getIsNeedToDisplaySideBar()):
        $helper   = Mage::helper('checkout'); ?>
        <div class="hdr-cart">
            <div class="hdr-cart-dropdown-box">
                <div class="hdr-cart-dropdown-chosen"><?php echo $vBagPrefix; ?><span id="top_cart_qty">0</span> <?php echo $this->__('item(s) in bag') ?></div>
                <div id="top_cart_content" class="hdr-cart-dropdown" style="display: none;">
                    Loading...
                </div>
            </div>
        </div>

        <script>
            var miniCartIsLoaded = false;
            Event.observe(document, 'personalisationcookie:render',
                function() {
                    miniCartIsLoaded = false;
                }
            );
            Event.observe(document, 'dom:loaded',
                function() {
                    $$(".hdr-cart-dropdown-box").each(
                        function(el) {
                            el.observe('click',
                                function(event) {
                                    $('top_cart_content').show();
                                    if (!miniCartIsLoaded) {
                                        var cartUrl = '<?php echo Mage::helper('minicart/cart')->getCartUrl() ?>' + '?cachebuster=' + new Date().valueOf();
                                        new Ajax.Request(cartUrl,{
                                            method: 'get',
                                            onSuccess: function(resp) {
                                                var minicart = resp.responseJSON;
                                                if (minicart && minicart.minicart) {
                                                    $('top_cart_content').update(minicart.minicart);
                                                    miniCartIsLoaded = true;
                                                    Event.fire(document, 'minicart:loaded');
                                                } else {
                                                    alert('An error has occurred. Please try again');
                                                }
                                            }
                                        });
                                    }
                                    event.stopPropagation(true);

                                }
                            );
                        }
                    );

                    $$('.page').each(
                        function (el) {
                            el.observe('click',
                                function() {
                                    $('top_cart_content').hide();
                                }
                            );
                        }
                    );

                }
            );
        </script>
    <?php endif; ?>
<?php else: ?>
    <?php
    $count = $this->getSummaryCount();
    $_items = $this->getRecentItems($count);
    if(count($_items)):
        echo $this->getChildHtml('top.cart.content');
    else: ?>
        <div class="no-items-in-cart"><?php echo Mage::helper('minicart')->getEmptyCartMessage();?></div>
    <?php endif ?>
<?php endif; ?>